// Data wisata lokal untuk MuterGresik
const wisataData = [{
        id: 1,
        nama: "Pantai Delegan",
        kategori: "alam",
        lokasi: "Ujungpangkah",
        gambar: "assets/img/delegan.jpg",
        rating: 4.1,
        tags: ["pantai", "sunset", "spot foto", "santai"],
        deskripsi: "Pantai Delegan merupakan salah satu destinasi wisata pantai unggulan di Kabupaten Gresik. Terletak di Kecamatan Manyar, pantai ini menawarkan pemandangan laut yang indah dengan pasir putih yang lembut. Pengunjung dapat menikmati suasana pantai yang tenang, bermain air, atau sekadar bersantai menikmati sunset yang memukau. Pantai ini juga dilengkapi dengan berbagai fasilitas pendukung yang membuat kunjungan wisata menjadi lebih nyaman.",
        jamBuka: "24 Jam",
        hargaTiket: "Rp 5.000 - Rp 15.000",
        fasilitas: ["Area Parkir Luas", "Warung Makan", "Toilet", "Mushola", "Gazebo", "Area Bermain Anak"],
        maps: "https://www.google.com/maps/search/?api=1&query=Pantai+Delegan"
    },
    {
        id: 2,
        nama: "Makam Sunan Giri",
        kategori: "religi",
        lokasi: "Gresik Kota",
        gambar: "assets/img/makam-giri.jpg",
        rating: 4.6,
        tags: ["view tinggi", "healing", "perbukitan", "trekking"],
        deskripsi: "Makam Sunan Giri adalah salah satu makam wali songo yang paling dihormati di Jawa Timur. Terletak di atas bukit di kawasan Giri, kompleks makam ini menjadi tujuan ziarah bagi ribuan peziarah setiap tahunnya. Selain nilai religius yang tinggi, kawasan ini juga menawarkan pemandangan kota Gresik yang indah dari ketinggian. Arsitektur bangunan yang megah dan suasana spiritual yang kental membuat tempat ini sangat istimewa. Pengunjung harus menaiki ratusan anak tangga untuk mencapai area makam utama.",
        jamBuka: "24 Jam (terbaik 08:00 - 16:00)",
        hargaTiket: "Gratis",
        fasilitas: ["Area Parkir", "Toilet", "Mushola", "Warung", "Air Minum", "Pemandu"],
        maps: "https://www.google.com/maps/search/?api=1&query=Makam+Sunan+Giri+Gresik"
    },
    {
        id: 3,
        nama: "Makam Siti Fatimah Binti Maimun",
        kategori: "religi",
        lokasi: "Gresik Kota",
        gambar: "assets/img/petilasan-siti.jpg",
        rating: 4.3,
        tags: ["healing", "sunyi", "hijau", "spot foto"],
        deskripsi: "Petilasan Siti Fatimah adalah situs bersejarah dan religius yang memiliki nilai penting dalam sejarah Islam Nusantara. Menurut kepercayaan setempat, tempat ini merupakan petilasan atau bekas tempat tinggal Siti Fatimah binti Maimun, tokoh penting dalam penyebaran Islam di Gresik. Kompleks ini memiliki bangunan kuno dengan arsitektur yang khas, halaman yang luas, dan suasana yang tenang. Banyak peziarah yang datang untuk berdoa dan mencari berkah di tempat ini.",
        jamBuka: "08:00 - 17:00",
        hargaTiket: "Gratis",
        fasilitas: ["Area Parkir", "Mushola", "Toilet", "Warung", "Pemandu"],
        maps: "https://www.google.com/maps/search/?api=1&query=Makam+Siti+Fatimah+Binti+Maimun"
    },
    {
        id: 4,
        nama: "Wisata Alam Gosari (Wagos)",
        kategori: "alam",
        lokasi: "Ujungpangkah",
        gambar: "assets/img/wagos.jpg",
        rating: 4.4,
        tags: ["alam", "hijau", "healing", "taman", "spot foto"],
        deskripsi: "Wisata Alam Gosari atau dikenal dengan sebutan Wagos adalah destinasi wisata alam yang menawarkan kesegaran udara pegunungan dengan pemandangan hijau yang asri. Terletak di kawasan Gosari, tempat ini memiliki udara yang sejuk, kebun teh yang luas, dan berbagai spot foto instagramable. Cocok untuk family gathering, camping, atau sekadar melepas penat dari hiruk pikuk kota. Wagos juga dilengkapi dengan berbagai wahana permainan dan area outbound.",
        jamBuka: "08:00 - 17:00",
        hargaTiket: "Rp 5.000 - Rp 15.000",
        fasilitas: ["Area Parkir", "Gazebo", "Warung Makan", "Toilet", "Spot Foto", "Area Outbound"],
        maps: "https://www.google.com/maps/search/?api=1&query=Wagos+Wisata+Alam+Gosari"
    },
    {
        id: 5,
        nama: "Bandar Grisse",
        kategori: "sejarah",
        lokasi: "Gresik Kota",
        gambar: "assets/img/bandar-grisse.jpg",
        rating: 4.7,
        tags: ["kuliner", "umkm", "spot foto", "santai", "sunset"],
        deskripsi: "Bandar Grisse adalah kawasan wisata kuliner tepi laut yang menawarkan pemandangan indah Selat Madura. Tempat ini menjadi destinasi favorit untuk menikmati sunset sambil mencicipi berbagai kuliner khas Gresik seperti seafood segar, sate bandeng, dan berbagai makanan laut lainnya. Suasana outdoor dengan angin laut yang sepoi-sepoi membuat pengalaman bersantap semakin berkesan. Bandar Grisse juga sering menjadi lokasi event budaya dan festival kuliner.",
        jamBuka: "15:00 - 23:00",
        hargaTiket: "Gratis",
        fasilitas: ["Area Parkir", "Toilet", "Mushola", "Spot Foto Sunset", "Dermaga", "Trotoar Estetik", "Lampu Taman Bergaya Kolonial", "Area Duduk", "Sentra Oleh-Oleh", "Bus Wisata", "Panggung Event"],
        maps: "https://www.google.com/maps/search/?api=1&query=Bandar+Grisse"
    },
    {
        id: 6,
        nama: "Alun-Alun Gresik",
        kategori: ["sejarah", "kuliner"],
        lokasi: "Gresik Kota",
        gambar: "assets/img/alun-alun.jpg",
        rating: 4.5,
        tags: ["kuliner", "umkm", "spot foto", "santai", "taman"],
        deskripsi: "Alun-Alun Gresik adalah pusat kota yang telah direnovasi menjadi ruang publik yang nyaman dan modern. Tempat ini menjadi gathering point bagi masyarakat Gresik untuk bersantai, berolahraga, atau sekadar berkumpul bersama keluarga. Di sekitar alun-alun terdapat banyak pedagang kuliner malam, wahana permainan anak, dan area terbuka hijau. Suasana malam di alun-alun sangat hidup dengan lampu-lampu yang indah dan berbagai aktivitas warga.",
        jamBuka: "24 Jam (ramai 17:00 - 22:00)",
        hargaTiket: "Gratis",
        fasilitas: ["Area Parkir", "Toilet", "Masjid", "Taman", "Playground", "Pedestrian", "Bangku Taman", "Pendopo", "Jogging Track"],
        maps: "https://www.google.com/maps/search/?api=1&query=Alun+Alun+Gresik"
    },
    {
        id: 7,
        nama: "Pantai Mayangkara",
        kategori: "alam",
        lokasi: "Bawean",
        gambar: "assets/img/mayangkara.jpg",
        rating: 4.8,
        tags: ["pantai", "alam", "sunset", "santai", "spot foto"],
        deskripsi: "Pantai Mayangkara adalah salah satu pantai terindah di Pulau Bawean. Dengan pasir putih yang halus dan air laut yang jernih berwarna biru kehijauan, pantai ini menawarkan pemandangan yang memukau. Ombak yang tenang membuatnya cocok untuk berenang dan snorkeling. Pengunjung dapat menikmati keindahan terumbu karang dan biota laut yang masih terjaga. Sunset di Pantai Mayangkara sangat spektakuler dan menjadi momen favorit para wisatawan.",
        jamBuka: "24 Jam",
        hargaTiket: "Gratis",
        fasilitas: ["Area Parkir", "Kamar Mandi", "Kamar Ganti", "Warung Wisata", "Mushola", "Gazebo", "Area Bermain"],
        maps: "https://www.google.com/maps/search/?api=1&query=Pantai+Mayangkara"
    },
    {
        id: 8,
        nama: "Danau Kastoba",
        kategori: "alam",
        lokasi: "Bawean",
        gambar: "assets/img/kastoba.jpg",
        rating: 4.5,
        tags: ["alam", "hijau", "healing", "sunyi"],
        deskripsi: "Danau Kastoba adalah danau alami yang menjadi ikon wisata Pulau Bawean. Dikelilingi oleh hutan tropis yang rimbun, danau ini memiliki air yang jernih dan suasana yang sangat tenang. Tempat ini sempurna untuk healing dan menikmati ketenangan alam. Pengunjung dapat mengelilingi danau dengan perahu, memancing, atau sekadar duduk menikmati pemandangan. Legenda lokal mengatakan bahwa danau ini memiliki nilai mistis dan dihuni oleh penunggu yang menjaga kelestariannya.",
        jamBuka: "07:00 - 17:00",
        hargaTiket: "Rp 5.000 - Rp. 10.000",
        fasilitas: ["Area Parkir", "Spot Foto", "Toilet", "Area Piknik", "Mushola"],
        maps: "https://www.google.com/maps/search/?api=1&query=Danau+Kastoba"
    },
    {
        id: 9,
        nama: "Air Terjun Laccar",
        kategori: "alam",
        lokasi: "Bawean",
        gambar: "assets/img/laccar.jpg",
        rating: 4.6,
        tags: ["alam", "hijau", "healing", "trekking", "tantangan"],
        deskripsi: "Air Terjun Laccar adalah destinasi wisata alam tersembunyi di Pulau Bawean. Untuk mencapai air terjun ini, pengunjung harus melakukan trekking melewati hutan tropis dengan medan yang cukup menantang. Namun, perjuangan akan terbayar dengan keindahan air terjun yang memesona dengan air yang jernih dan segar. Suasana di sekitar air terjun sangat sejuk dan tenang, cocok untuk refreshing dan menikmati keindahan alam yang masih alami. Kolam di bawah air terjun aman untuk berenang.",
        jamBuka: "08:00 - 16:00",
        hargaTiket: "Rp 3.000 - 5.000",
        fasilitas: ["Area Parkir", "Jalur Trekking", "Area Berenang", "Warung Sederhana", "Tempat Peristirahatan"],
        maps: "https://www.google.com/maps/search/?api=1&query=Air+Terjun+Laccar"
    },
    {
        id: 10,
        nama: "Pantai Tanjung Gaang",
        kategori: "alam",
        lokasi: "Bawean",
        gambar: "assets/img/tanjung-gaang.jpg",
        rating: 4.6,
        tags: ["pantai", "sunset", "spot foto", "santai"],
        deskripsi: "Pantai Tanjung Gaang terletak di ujung barat Pulau Bawean dan menawarkan pemandangan sunset yang luar biasa indah. Pantai ini memiliki karakteristik unik dengan batu-batu karang besar yang tersebar di sepanjang bibir pantai, menciptakan spot foto yang instagramable. Air lautnya yang jernih dan ombak yang tenang membuat pantai ini cocok untuk berenang dan bermain air. Suasana pantai yang relatif sepi menjadikannya tempat yang tepat untuk menikmati ketenangan dan keindahan alam.",
        jamBuka: "24 Jam",
        hargaTiket: "Rp 5.000",
        fasilitas: ["Area Parkir", "Warung Makan", "Toilet", "Spot Foto"],
        maps: "https://www.google.com/maps/search/?api=1&query=Pantai+Tanjung+Gaang"
    },
    {
        id: 11,
        nama: "Wisata Mangrove Hijau Daun",
        kategori: "alam",
        lokasi: "Bawean",
        gambar: "assets/img/mangrove-hijau-daun.jpeg",
        rating: 4.5,
        tags: ["alam", "hijau", "healing", "spot foto", "taman"],
        deskripsi: "Wisata Mangrove Hijau Daun Bawean adalah kawasan konservasi mangrove yang telah dikembangkan menjadi destinasi ekowisata. Pengunjung dapat menyusuri jembatan kayu yang membelah hutan mangrove sambil menikmati keindahan ekosistem pesisir. Tempat ini menjadi habitat berbagai jenis burung, kepiting, dan biota laut lainnya. Selain menikmati keindahan alam, pengunjung juga dapat belajar tentang pentingnya konservasi mangrove. Spot foto dengan latar belakang hutan mangrove sangat populer di kalangan wisatawan.",
        jamBuka: "07:00 - 17:00",
        hargaTiket: "Rp 5.000",
        fasilitas: ["Jembatan Kayu", "Area Parkir", "Spot Foto", "Gazebo", "Toilet", "Pemandu Ekowisata"],
        maps: "https://www.google.com/maps/search/?api=1&query=Wisata+Mangrove+Hijau+Daun"
    },
    {
        id: 12,
        nama: "Kampung Kemasan",
        kategori: "sejarah",
        lokasi: "Gresik Kota",
        gambar: "assets/img/kampung-kemasan.jpeg",
        rating: 4.7,
        tags: ["kuliner", "umkm", "spot foto", "santai", "taman"],
        deskripsi: "Kampung Kemasan adalah kawasan kota lama di Gresik dengan arsitektur unik yang merupakan perpaduan gaya Eropa dan Tiongkok.",
        jamBuka: "24 Jam",
        hargaTiket: "Gratis",
        fasilitas: ["Area Parkir", "Spot Foto", "Toilet", "Pemandu Wisata", "Mushola"],
        maps: "https://www.google.com/maps/search/?api=1&query=Kampung+Kemasan"
    },
    {
        id: 13,
        nama: "Balai keling kroman",
        kategori: "alam",
        lokasi: "Gresik Kota",
        gambar: "assets/img/balai-keling.jpeg",
        rating: 4.4,
        tags: ["area parkir", "spot foto", "santai"],
        deskripsi: "Kampung Kemasan adalah kawasan kota lama di Gresik dengan arsitektur unik yang merupakan perpaduan gaya Eropa dan Tiongkok.",
        jamBuka: "24 Jam",
        hargaTiket: "Gratis",
        fasilitas: ["Area Parkir", "Spot Foto", "Toilet", "Spot Foto Warna-warni", "Dermaga Nelayan", "Mushola", "Area Santai"],
        maps: "https://www.google.com/maps/search/?api=1&query=Balai+Keling+Kroman"
    },
    {
        id: 14,
        nama: "Bukit Surowiti Panceng",
        kategori: "kuliner",
        lokasi: "Ujungpangkah",
        gambar: "assets/img/bukit-surowiti.jpeg",
        rating: 4.7,
        tags: ["view tinggi", "healing", "perbukitan", "trekking"],
        deskripsi: "Bukit Surowiti adalah destinasi wisata perbukitan yang memukau di Gresik dengan pesona alam yang indah sekaligus nilai sejarah dan religi yang kuat sebagai petilasan Sunan Kalijaga, menawarkan pengalaman trekking, berziarah, dan menikmati panorama hijau sambil belajar tentang budaya dan sejarah setempat.",
        jamBuka: "24 Jam",
        hargaTiket: "Rp. 10.000",
        fasilitas: ["Area Parkir", "Toilet", "Mushola", "Area Camping", "Area Foto", "Jalur Trekking"],
        maps: "https://www.google.com/maps/search/?api=1&query=Bukit+Surowiti+Panceng"
    },
    {
        id: 15,
        nama: "Rumah Makan Bandeng Pak Elan II",
        kategori: "kuliner",
        lokasi: "Gresik Kota",
        gambar: "assets/img/pak-elan.jpeg",
        rating: 4.4,
        tags: ["kuliner", "umkm"],
        deskripsi: "Rumah Makan Bandeng Pak Elan II adalah destinasi kuliner legendaris di Gresik yang terkenal dengan menu bandeng bakar tanpa duri yang lezat, suasana resto yang luas dan nyaman, serta layanan ramah yang membuat setiap pengunjung betah menikmati kelezatan khas daerah ini.",
        jamBuka: "24 Jam",
        hargaTiket: "Gratis",
        fasilitas: ["Jembatan Kayu", "Area Parkir", "Spot Foto", "Gazebo", "Toilet", "Pemandu Ekowisata"],
        maps: "https://www.google.com/maps/search/?api=1&query=Rumah+Makan+Bandeng+Pak+Elan+II"
    },
    {
        id: 16,
        nama: "Otak-Otak Bandeng Bu Muzanah",
        kategori: "kuliner",
        lokasi: "Gresik Kota",
        gambar: "assets/img/bu-muzanah.jpeg",
        rating: 4.6,
        tags: ["kuliner", "umkm"],
        deskripsi: "Otak-Otak Bandeng Bu Muzanah merupakan pusat oleh-oleh khas Gresik yang sangat populer, menyediakan olahan otak-otak bandeng dengan cita rasa autentik yang maknyus, serta berbagai produk olahan bandeng lainnya seperti pepes tanpa duri dan bandeng bakar yang dipajang dalam konsep swalayan modern.",
        jamBuka: "24 Jam",
        hargaTiket: "Gratis",
        fasilitas: ["Jembatan Kayu", "Area Parkir", "Spot Foto", "Gazebo", "Toilet", "Pemandu Ekowisata"],
        maps: "https://www.google.com/maps/search/?api=1&query=Bu+Muzanah+Store"
    },
    {
        id: 17,
        nama: "Nasi Krawu Bu Tiban",
        kategori: "kuliner",
        lokasi: "Gresik Kota",
        gambar: "assets/img/nasi-krawu-tiban.jpeg",
        rating: 4.6,
        tags: ["kuliner", "umkm"],
        deskripsi: "Nasi Krawu Bu Tiban adalah salah satu tempat terbaik untuk menikmati nasi krawu khas Gresik yang menggoyang lidah, di mana nasi pulen hangat disajikan dalam daun pisang bersama sayuran, daging sapi, jeroan, sambal petis, dan serundeng, menciptakan perpaduan rasa tradisional yang tak terlupakan di Kabupaten Gresik.",
        jamBuka: "24 Jam",
        hargaTiket: "Gratis",
        fasilitas: ["kuliner", "umkm", "Area Parkir", "Toilet", "Mushola"],
        maps: "https://www.google.com/maps/search/?api=1&query=Nasi+Krawu+Buk+Tiban+Trate"
    },
    {
        id: 18,
        nama: "Rawon Tulang Pak Nawi",
        kategori: "kuliner",
        lokasi: "Gresik Kota",
        gambar: "assets/img/rawon-tulang-pak-nawi.jpg",
        rating: 4.5,
        tags: ["kuliner", "umkm"],
        deskripsi: "Rawon Tulang Pak Nawi adalah kuliner legendaris di Gresik yang terkenal dengan kuah hitamnya yang kaya rempah, daging tulang yang empuk dan lumer di mulut, serta sambal pedas khas yang melengkapi kenikmatannya.",
        jamBuka: "24 Jam",
        hargaTiket: "Gratis",
        fasilitas: ["kuliner", "umkm", "Area Parkir", "Toilet", "Mushola"],
        maps: "https://www.google.com/maps/search/?api=1&query=Rawon+Tulang+Pak+Nawi"
    },
    {
        id: 19,
        nama: "Sego Krawu dan Sego Menir Buk Marjani",
        kategori: "kuliner",
        lokasi: "Gresik Kota",
        gambar: "assets/img/sego-krawu-dan-sego-menir-buk-marjani.jpeg",
        rating: 4.6,
        tags: ["kuliner", "umkm"],
        deskripsi: "Sego Krawu dan Sego Menir Buk Marjani adalah kuliner legendaris khas Gresik yang terkenal dengan nasi pulen yang disajikan dengan aneka lauk seperti daging semur, jeroan, sambal petis pedas, dan serundeng, menawarkan cita rasa otentik yang kaya dan selalu ramai dikunjungi oleh pecinta kuliner.",
        jamBuka: "05.00 - 20.00",
        hargaTiket: "Gratis",
        fasilitas: ["kuliner", "umkm", "Area Parkir", "Toilet", "Mushola"],
        maps: "https://www.google.com/maps/search/?api=1&query=Nasi+Krawu+Buk+Marjani"
    },
    {
        id: 20,
        nama: "Sego Roomo Mbak Dewi",
        kategori: "kuliner",
        lokasi: "Gresik Kota",
        gambar: "assets/img/sego-roome-mbak-dewi.jpeg",
        rating: 4.7,
        tags: ["kuliner", "umkm"],
        deskripsi: "Sego Roomo Mbak Dewi adalah kuliner khas Gresik berupa bubur nasi kuning yang disajikan dengan sayuran rebus khas seperti daun bakau dan daun alur, kerupuk, sambal, dan taburan koya kelapa gurih, yang menjadi favorit banyak warga dan wisatawan karena cita rasanya yang unik dan lezat.",
        jamBuka: "06.00 - 12.00",
        hargaTiket: "Gratis",
        fasilitas: ["kuliner", "umkm", "Area Parkir", "Toilet", "Mushola"],
        maps: "https://www.google.com/maps/search/?api=1&query=Sego+Roomo+Mbak+Dewi"
    }
];

// Export data untuk digunakan di file lain
if (typeof module !== 'undefined' && module.exports) {
    module.exports = wisataData;
}
